# ETL PROCESSING

In [1]:
# Import dependencies
import pandas as pd
import re

## Extract

In [2]:
# Read data
data = pd.read_csv("data/Censo_2020.csv")

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data.head()

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,LONGITUD,LATITUD,ALTITUD,POBTOT,...,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC,TAMLOC
0,0,Total nacional,0,Total nacional,0,Total nacional,NaN,NaN,NaN,126014024,...,30775898,18307193,15211306,6616141,4047100,1788552,3170894,15108204,852871,*
1,0,Total nacional,0,Total nacional,9998,Localidades de una vivienda,NaN,NaN,NaN,250354,...,47005,8385,18981,1732,1113,12775,14143,51293,7154,*
2,0,Total nacional,0,Total nacional,9999,Localidades de dos viviendas,NaN,NaN,NaN,147125,...,25581,5027,11306,971,708,8247,10065,29741,5283,*
3,1,Aguascalientes,0,Total de la entidad Aguascalientes,0,Total de la Entidad,NaN,NaN,NaN,1425607,...,359895,236003,174089,98724,70126,6021,15323,128996,1711,*
4,1,Aguascalientes,0,Total de la entidad Aguascalientes,9998,Localidades de una vivienda,NaN,NaN,NaN,3697,...,732,205,212,48,41,39,62,530,20,*

In [4]:
data.describe()

,ENTIDAD,MUN,LOC,POBTOT,VIVTOT,TVIVHAB
count,195662.000000,195662.000000,195662.000000,1.956620e+05,1.956620e+05,1.956620e+05
mean,16.806743,59.699400,623.572221,2.582252e+03,9.000329e+02,7.218171e+02
std,8.940159,81.370934,1502.609425,2.931486e+05,1.019782e+05,8.195072e+04
min,0.000000,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000,12.000000,45.000000,4.000000e+00,2.000000e+00,1.000000e+00
50%,16.000000,33.000000,162.000000,1.600000e+01,7.000000e+00,4.000000e+00
75%,25.000000,73.000000,531.000000,1.470000e+02,5.400000e+01,3.800000e+01
max,32.000000,570.000000,9999.000000,1.260140e+08,4.390344e+07,3.523346e+07

In [5]:
data.shape

(195662, 231)

## Transform

In [6]:
# First, we remove all the blank values from rows that sum up total, since they don't have any latitude or longitude we can use
data = data.dropna()

In [7]:
# Then, we create a function to change the coordinates to the correct type
def dms2dd(s):
    # example: s = """0Â°51'56.29"S"""
    degrees, minutes, seconds, direction = re.split('[Â°\'"]+', s)
    dd = float(degrees) + float(minutes)/60 + float(seconds)/(60*60);
    if direction in ('S','W'):
        dd*= -1
    return dd

In [8]:
# We use the function to change both latitude and longitude columns
data['LATITUD'] = data['LATITUD'].apply(dms2dd)
data['LONGITUD'] = data['LONGITUD'].apply(dms2dd)*-1

In [9]:
# Here we print all the columns to see which ones will be left on the final Dataframe
for x in data:
    print(x)

ENTIDAD
NOM_ENT
MUN
NOM_MUN
LOC
NOM_LOC
LONGITUD
LATITUD
ALTITUD
POBTOT
POBFEM
POBMAS
P_0A2
P_0A2_F
P_0A2_M
P_3YMAS
P_3YMAS_F
P_3YMAS_M
P_5YMAS
P_5YMAS_F
P_5YMAS_M
P_12YMAS
P_12YMAS_F
P_12YMAS_M
P_15YMAS
P_15YMAS_F
P_15YMAS_M
P_18YMAS
P_18YMAS_F
P_18YMAS_M
P_3A5
P_3A5_F
P_3A5_M
P_6A11
P_6A11_F
P_6A11_M
P_8A14
P_8A14_F
P_8A14_M
P_12A14
P_12A14_F
P_12A14_M
P_15A17
P_15A17_F
P_15A17_M
P_18A24
P_18A24_F
P_18A24_M
P_15A49_F
P_60YMAS
P_60YMAS_F
P_60YMAS_M
REL_H_M
POB0_14
POB15_64
POB65_MAS
PROM_HNV
PNACENT
PNACENT_F
PNACENT_M
PNACOE
PNACOE_F
PNACOE_M
PRES2015
PRES2015_F
PRES2015_M
PRESOE15
PRESOE15_F
PRESOE15_M
P3YM_HLI
P3YM_HLI_F
P3YM_HLI_M
P3HLINHE
P3HLINHE_F
P3HLINHE_M
P3HLI_HE
P3HLI_HE_F
P3HLI_HE_M
P5_HLI
P5_HLI_NHE
P5_HLI_HE
PHOG_IND
POB_AFRO
POB_AFRO_F
POB_AFRO_M
PCON_DISC
PCDISC_MOT
PCDISC_VIS
PCDISC_LENG
PCDISC_AUD
PCDISC_MOT2
PCDISC_MEN
PCON_LIMI
PCLIM_CSB
PCLIM_VIS
PCLIM_HACO
PCLIM_OAUD
PCLIM_MOT2
PCLIM_RE_CO
PCLIM_PMEN
PSIND_LIM
P3A5_NOA
P3A5_NOA_F
P3A5_NOA_M
P6A11_NOA
P6A11_NOAF
P6A11_NOAM
P12A14NOA
P12A14NOAF
P12A14NOAM
P15A17A
P15A17A_F
P15A17A_M
P18A24A
P18A24A_F
P18A24A_M
P8A14AN
P8A14AN_F
P8A14AN_M
P15YM_AN
P15YM_AN_F
P15YM_AN_M
P15YM_SE
P15YM_SE_F
P15YM_SE_M
P15PRI_IN
P15PRI_INF
P15PRI_INM
P15PRI_CO
P15PRI_COF
P15PRI_COM
P15SEC_IN
P15SEC_INF
P15SEC_INM
P15SEC_CO
P15SEC_COF
P15SEC_COM
P18YM_PB
P18YM_PB_F
P18YM_PB_M
GRAPROES
GRAPROES_F
GRAPROES_M
PEA
PEA_F
PEA_M
PE_INAC
PE_INAC_F
PE_INAC_M
POCUPADA
POCUPADA_F
POCUPADA_M
PDESOCUP
PDESOCUP_F
PDESOCUP_M
PSINDER
PDER_SS
PDER_IMSS
PDER_ISTE
PDER_ISTEE
PAFIL_PDOM
PDER_SEGP
PDER_IMSSB
PAFIL_IPRIV
PAFIL_OTRAI
P12YM_SOLT
P12YM_CASA
P12YM_SEPA
PCATOLICA
PRO_CRIEVA
POTRAS_REL
PSIN_RELIG
TOTHOG
HOGJEF_F
HOGJEF_M
POBHOG
PHOGJEF_F
PHOGJEF_M
VIVTOT
TVIVHAB
TVIVPAR
VIVPAR_HAB
TVIVPARHAB
VIVPAR_DES
VIVPAR_UT
OCUPVIVPAR
PROM_OCUP
PRO_OCUP_C
VPH_PISODT
VPH_PISOTI
VPH_1DOR
VPH_2YMASD
VPH_1CUART
VPH_2CUART
VPH_3YMASC
VPH_C_ELEC
VPH_S_ELEC
VPH_AGUADV
VPH_AEASP
VPH_AGUAFV
VPH_TINACO
VPH_CISTER
VPH_EXCSA
VPH_LETR
VPH_DRENAJ
VPH_NODREN
VPH_C_SERV
VPH_NDEAED
VPH_DSADMA
VPH_NDACMM
VPH_SNBIEN
VPH_REFRI
VPH_LAVAD
VPH_HMICRO
VPH_AUTOM
VPH_MOTO
VPH_BICI
VPH_RADIO
VPH_TV
VPH_PC
VPH_TELEF
VPH_CEL
VPH_INTER
VPH_STVP
VPH_SPMVPI
VPH_CVJ
VPH_SINRTV
VPH_SINLTC
VPH_SINCINT
VPH_SINTIC
TAMLOC

In [10]:
# First, we create a dataframe only with the columns we need
final_df = data[["ENTIDAD","NOM_ENT", "MUN", "NOM_MUN","NOM_LOC","LONGITUD","LATITUD","POBTOT","POBFEM","POBMAS","PEA","TVIVPARHAB","VPH_RADIO","VPH_TV","VPH_PC","VPH_TELEF","VPH_CEL","VPH_INTER","VPH_STVP","VPH_SPMVPI","VPH_CVJ"]]
# Then, we replace the asterisk values with zeros and "N/D" values we found when exploring data
final_df = final_df.replace("*",0)
final_df = final_df.replace("N/D",0)

In [11]:
final_df

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,NOM_LOC,LONGITUD,LATITUD,POBTOT,POBFEM,POBMAS,...,TVIVPARHAB,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
7,1,Aguascalientes,1,Aguascalientes,Aguascalientes,-102.296047,21.879823,863893,444725,419168,...,246116,204535,237274,130384,112002,232793,169675,123670,77719,53589
8,1,Aguascalientes,1,Aguascalientes,Granja Adelita,-102.373531,21.871875,5,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,Aguascalientes,1,Aguascalientes,Agua Azul,-102.357122,21.883756,41,17,24,...,12,11,11,5,2,11,4,5,2,1
10,1,Aguascalientes,1,Aguascalientes,Los Arbolitos [Rancho],-102.357295,21.780181,8,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,Aguascalientes,1,Aguascalientes,Ardillas de Abajo (Las Ardillas),-102.191921,21.945068,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195656,32,Zacatecas,58,Santa MarÃ­a de la Paz,Los Trigos (Mesa de los Trigos),-103.241053,21.497599,89,43,46,...,23,13,18,2,0,19,1,5,0,0
195657,32,Zacatecas,58,Santa MarÃ­a de la Paz,Mesa Grande,-103.414701,21.553438,165,88,77,...,49,29,44,6,29,24,9,13,0,0
195658,32,Zacatecas,58,Santa MarÃ­a de la Paz,San Isidro,-103.337268,21.486425,1,0,0,...,0,0,0,0,0,0,0,0,0,0
195659,32,Zacatecas,58,Santa MarÃ­a de la Paz,San Miguel TepetitlÃ¡n,-103.335932,21.504213,97,50,47,...,31,20,26,4,1,21,12,21,1,1
195660,32,Zacatecas,58,Santa MarÃ­a de la Paz,San Rafael,-103.372259,21.527595,3,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# We realized the columns were "object" type because of the asterisk and N/D values we removed before
final_df.dtypes

ENTIDAD         int64
NOM_ENT        object
MUN             int64
NOM_MUN        object
NOM_LOC        object
LONGITUD      float64
LATITUD       float64
POBTOT          int64
POBFEM         object
POBMAS         object
PEA            object
TVIVPARHAB     object
VPH_RADIO      object
VPH_TV         object
VPH_PC         object
VPH_TELEF      object
VPH_CEL        object
VPH_INTER      object
VPH_STVP       object
VPH_SPMVPI     object
VPH_CVJ        object
dtype: object

In [13]:
# So here we convert the columns to integer type
final_df[final_df.columns[7:].to_list()] = final_df[final_df.columns[7:].to_list()].astype(int)

In [14]:
final_df.dtypes

ENTIDAD         int64
NOM_ENT        object
MUN             int64
NOM_MUN        object
NOM_LOC        object
LONGITUD      float64
LATITUD       float64
POBTOT          int32
POBFEM          int32
POBMAS          int32
PEA             int32
TVIVPARHAB      int32
VPH_RADIO       int32
VPH_TV          int32
VPH_PC          int32
VPH_TELEF       int32
VPH_CEL         int32
VPH_INTER       int32
VPH_STVP        int32
VPH_SPMVPI      int32
VPH_CVJ         int32
dtype: object

In [15]:
# Removing latitude and longitude from dataframe and grouping by municipality so we can send it to database
final_df = final_df.groupby(['ENTIDAD',"NOM_ENT","MUN","NOM_MUN"])[final_df.columns[7:].to_list()].apply(lambda x : x.astype(int).sum()).reset_index()

In [16]:
final_df.head()

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,POBTOT,POBFEM,POBMAS,PEA,TVIVPARHAB,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,1,Aguascalientes,1,Aguascalientes,948990,486138,460305,485108,266427,221026,256747,136845,116612,251390,178518,130206,80923,56106
1,1,Aguascalientes,2,Asientos,51536,26097,25079,21269,12442,8821,11707,2794,1685,10592,4494,3848,590,551
2,1,Aguascalientes,3,Calvillo,58250,29584,28430,25854,15471,10658,14566,3994,4715,13602,6537,4736,1380,1350
3,1,Aguascalientes,4,CosÃ­o,17000,8626,8187,6919,3887,2711,3629,996,549,3380,1725,1650,221,190
4,1,Aguascalientes,5,JesÃºs MarÃ­a,129929,65492,63978,65608,33101,27184,31811,15659,12479,31302,19879,13441,9283,6570

In [17]:
final_df.to_csv("data/Censo.csv", index = False)

## Load